namespace UI
{
    partial class FrmControlCambiosProductos
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.ComboBox cbProductos;
        private System.Windows.Forms.Button btnCargar;
        private System.Windows.Forms.DataGridView dgvHistorial;
        private System.Windows.Forms.DataGridView dgvActual;
        private System.Windows.Forms.Button btnRevertir;
        private System.Windows.Forms.Label lblProducto;
        private System.Windows.Forms.Label lblHistorial;
        private System.Windows.Forms.Label lblActual;
        private System.Windows.Forms.SplitContainer splitMain;
        private void InitializeComponent()
        {
            cbProductos = new ComboBox();
            btnCargar = new Button();
            dgvHistorial = new DataGridView();
            dgvActual = new DataGridView();
            btnRevertir = new Button();
            lblProducto = new Label();
            lblHistorial = new Label();
            lblActual = new Label();
            splitMain = new SplitContainer();
            ((System.ComponentModel.ISupportInitialize)dgvHistorial).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvActual).BeginInit();
            ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
            splitMain.Panel1.SuspendLayout();
            splitMain.Panel2.SuspendLayout();
            splitMain.SuspendLayout();
            SuspendLayout();
            cbProductos.DropDownStyle = ComboBoxStyle.DropDownList;
            cbProductos.Location = new Point(149, 15);
            cbProductos.Name = "cbProductos";
            cbProductos.Size = new Size(320, 31);
            cbProductos.TabIndex = 1;
            btnCargar.Location = new Point(489, 15);
            btnCargar.Name = "btnCargar";
            btnCargar.Size = new Size(120, 28);
            btnCargar.TabIndex = 2;
            btnCargar.Text = "Cargar";
            btnCargar.Click += btnCargar_Click;
            dgvHistorial.ColumnHeadersHeight = 29;
            dgvHistorial.Dock = DockStyle.Fill;
            dgvHistorial.Location = new Point(0, 20);
            dgvHistorial.Name = "dgvHistorial";
            dgvHistorial.ReadOnly = true;
            dgvHistorial.RowHeadersWidth = 51;
            dgvHistorial.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvHistorial.Size = new Size(640, 580);
            dgvHistorial.TabIndex = 0;
            dgvHistorial.SelectionChanged += dgvHistorial_SelectionChanged;
            dgvActual.ColumnHeadersHeight = 29;
            dgvActual.Dock = DockStyle.Fill;
            dgvActual.Location = new Point(0, 20);
            dgvActual.Name = "dgvActual";
            dgvActual.ReadOnly = true;
            dgvActual.RowHeadersWidth = 51;
            dgvActual.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvActual.Size = new Size(596, 580);
            dgvActual.TabIndex = 0;
            btnRevertir.Location = new Point(630, 15);
            btnRevertir.Name = "btnRevertir";
            btnRevertir.Size = new Size(200, 28);
            btnRevertir.TabIndex = 3;
            btnRevertir.Text = "Revertir seleccionado";
            btnRevertir.Enabled = false;
            btnRevertir.Click += btnRevertir_Click;
            lblProducto.Location = new Point(20, 20);
            lblProducto.Name = "lblProducto";
            lblProducto.Size = new Size(100, 23);
            lblProducto.TabIndex = 0;
            lblProducto.Text = "Producto";
            lblHistorial.Dock = DockStyle.Top;
            lblHistorial.Location = new Point(0, 0);
            lblHistorial.Name = "lblHistorial";
            lblHistorial.Size = new Size(640, 20);
            lblHistorial.TabIndex = 1;
            lblHistorial.Text = "Historial";
            lblActual.Dock = DockStyle.Top;
            lblActual.Location = new Point(0, 0);
            lblActual.Name = "lblActual";
            lblActual.Size = new Size(596, 20);
            lblActual.TabIndex = 1;
            lblActual.Text = "Actual";
            splitMain.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            splitMain.Location = new Point(8, 60);
            splitMain.Name = "splitMain";
            splitMain.Panel1.Controls.Add(dgvHistorial);
            splitMain.Panel1.Controls.Add(lblHistorial);
            splitMain.Panel2.Controls.Add(dgvActual);
            splitMain.Panel2.Controls.Add(lblActual);
            splitMain.Size = new Size(1557, 670);
            splitMain.SplitterDistance = 778;
            splitMain.TabIndex = 99;
            ClientSize = new Size(1573, 794);
            Controls.Add(lblProducto);
            Controls.Add(cbProductos);
            Controls.Add(btnCargar);
            Controls.Add(splitMain);
            Controls.Add(btnRevertir);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmControlCambiosProductos";
            Text = "Control de Cambios - Productos";
            Load += FrmControlCambiosProductos_Load;
            ((System.ComponentModel.ISupportInitialize)dgvHistorial).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvActual).EndInit();
            splitMain.Panel1.ResumeLayout(false);
            splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
            splitMain.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
