namespace UI
{
    partial class FrmClientes
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.DataGridView dgvClientes;
        private System.Windows.Forms.TextBox txtNombreCompleto;
        private System.Windows.Forms.TextBox txtDireccion;
        private System.Windows.Forms.TextBox txtTelefono;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.ComboBox cbZona;
        private System.Windows.Forms.CheckBox chkActivo;
        private System.Windows.Forms.Button btnAgregar;
        private System.Windows.Forms.Button btnModificar;
        private System.Windows.Forms.Button btnEliminar;
        private System.Windows.Forms.Button btnGrabar;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Button btnToggleEliminados;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            dgvClientes = new DataGridView();
            txtNombreCompleto = new TextBox();
            txtDireccion = new TextBox();
            txtTelefono = new TextBox();
            txtEmail = new TextBox();
            cbZona = new ComboBox();
            chkActivo = new CheckBox();
            btnAgregar = new Button();
            btnModificar = new Button();
            btnEliminar = new Button();
            btnGrabar = new Button();
            btnCancelar = new Button();
            btnToggleEliminados = new Button();
            lblNombreCompleto = new Label();
            lblDireccion = new Label();
            lblTelefono = new Label();
            lblEmail = new Label();
            lblZona = new Label();
            pnlInputs = new FlowLayoutPanel();
            pnlBotones = new FlowLayoutPanel();
            ((System.ComponentModel.ISupportInitialize)dgvClientes).BeginInit();
            SuspendLayout();
            dgvClientes.AllowUserToAddRows = false;
            dgvClientes.AllowUserToDeleteRows = false;
            dgvClientes.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvClientes.Dock = DockStyle.Fill;
            dgvClientes.MultiSelect = false;
            dgvClientes.Name = "dgvClientes";
            dgvClientes.ReadOnly = true;
            dgvClientes.RowHeadersWidth = 51;
            dgvClientes.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvClientes.TabIndex = 0;
            dgvClientes.CellClick += dgvClientes_CellClick;
            dgvClientes.SelectionChanged += dgvClientes_SelectionChanged;
            pnlInputs.AutoScroll = true;
            pnlInputs.AutoSize = true;
            pnlInputs.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlInputs.Dock = DockStyle.Top;
            pnlInputs.FlowDirection = FlowDirection.LeftToRight;
            pnlInputs.Location = new Point(0, 0);
            pnlInputs.Name = "pnlInputs";
            pnlInputs.Padding = new Padding(12, 10, 12, 10);
            pnlInputs.Size = new Size(1150, 140);
            pnlInputs.TabIndex = 20;
            pnlInputs.WrapContents = true;
            pnlBotones.AutoScroll = true;
            pnlBotones.AutoSize = true;
            pnlBotones.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlBotones.Dock = DockStyle.Top;
            pnlBotones.FlowDirection = FlowDirection.LeftToRight;
            pnlBotones.Location = new Point(0, 140);
            pnlBotones.Name = "pnlBotones";
            pnlBotones.Padding = new Padding(12, 5, 12, 10);
            pnlBotones.Size = new Size(1150, 60);
            pnlBotones.TabIndex = 21;
            pnlBotones.WrapContents = true;
            lblNombreCompleto.AutoSize = true;
            lblNombreCompleto.Margin = new Padding(8, 0, 8, 0);
            lblNombreCompleto.Name = "lblNombreCompleto";
            lblNombreCompleto.Size = new Size(149, 23);
            lblNombreCompleto.TabIndex = 15;
            lblNombreCompleto.Tag = "NombreCompleto";
            lblNombreCompleto.Text = "Nombre Completo:";
            txtNombreCompleto.Margin = new Padding(4, 0, 20, 10);
            txtNombreCompleto.Name = "txtNombreCompleto";
            txtNombreCompleto.PlaceholderText = "Nombre completo del cliente";
            txtNombreCompleto.Size = new Size(280, 30);
            txtNombreCompleto.TabIndex = 1;
            lblDireccion.AutoSize = true;
            lblDireccion.Margin = new Padding(8, 0, 8, 0);
            lblDireccion.Name = "lblDireccion";
            lblDireccion.Size = new Size(91, 23);
            lblDireccion.TabIndex = 16;
            lblDireccion.Tag = "Direccion";
            lblDireccion.Text = "Dirección:";
            txtDireccion.Margin = new Padding(4, 0, 20, 10);
            txtDireccion.Name = "txtDireccion";
            txtDireccion.PlaceholderText = "Dirección";
            txtDireccion.Size = new Size(250, 30);
            txtDireccion.TabIndex = 2;
            lblTelefono.AutoSize = true;
            lblTelefono.Margin = new Padding(8, 0, 8, 0);
            lblTelefono.Name = "lblTelefono";
            lblTelefono.Size = new Size(82, 23);
            lblTelefono.TabIndex = 17;
            lblTelefono.Tag = "Telefono";
            lblTelefono.Text = "Teléfono:";
            txtTelefono.Margin = new Padding(4, 0, 20, 10);
            txtTelefono.Name = "txtTelefono";
            txtTelefono.PlaceholderText = "Teléfono";
            txtTelefono.Size = new Size(180, 30);
            txtTelefono.TabIndex = 3;
            lblEmail.AutoSize = true;
            lblEmail.Margin = new Padding(8, 10, 8, 0);
            lblEmail.Name = "lblEmail";
            lblEmail.Size = new Size(58, 23);
            lblEmail.TabIndex = 18;
            lblEmail.Tag = "Email";
            lblEmail.Text = "Email:";
            txtEmail.Margin = new Padding(4, 5, 20, 10);
            txtEmail.Name = "txtEmail";
            txtEmail.PlaceholderText = "Email (opcional)";
            txtEmail.Size = new Size(300, 30);
            txtEmail.TabIndex = 4;
            lblZona.AutoSize = true;
            lblZona.Margin = new Padding(8, 10, 8, 0);
            lblZona.Name = "lblZona";
            lblZona.Size = new Size(53, 23);
            lblZona.TabIndex = 19;
            lblZona.Tag = "Zona";
            lblZona.Text = "Zona:";
            cbZona.DropDownStyle = ComboBoxStyle.DropDownList;
            cbZona.Margin = new Padding(4, 5, 20, 10);
            cbZona.Name = "cbZona";
            cbZona.Size = new Size(220, 31);
            cbZona.TabIndex = 5;
            chkActivo.AutoSize = true;
            chkActivo.Checked = true;
            chkActivo.CheckState = System.Windows.Forms.CheckState.Checked;
            chkActivo.Margin = new Padding(8, 8, 20, 10);
            chkActivo.Name = "chkActivo";
            chkActivo.Size = new Size(79, 27);
            chkActivo.TabIndex = 6;
            chkActivo.Tag = "Activo";
            chkActivo.Text = "Activo";
            chkActivo.UseVisualStyleBackColor = true;
            btnAgregar.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            btnAgregar.ForeColor = System.Drawing.Color.White;
            btnAgregar.FlatStyle = FlatStyle.Flat;
            btnAgregar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnAgregar.Margin = new Padding(8, 5, 8, 5);
            btnAgregar.Name = "btnAgregar";
            btnAgregar.Size = new Size(130, 40);
            btnAgregar.TabIndex = 7;
            btnAgregar.Tag = "Agregar";
            btnAgregar.Text = "Agregar";
            btnAgregar.UseVisualStyleBackColor = false;
            btnAgregar.Click += btnAgregar_Click;
            btnModificar.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            btnModificar.ForeColor = System.Drawing.Color.White;
            btnModificar.FlatStyle = FlatStyle.Flat;
            btnModificar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnModificar.Enabled = false;
            btnModificar.Margin = new Padding(8, 5, 8, 5);
            btnModificar.Name = "btnModificar";
            btnModificar.Size = new Size(140, 40);
            btnModificar.TabIndex = 8;
            btnModificar.Tag = "Modificar";
            btnModificar.Text = "Modificar";
            btnModificar.UseVisualStyleBackColor = false;
            btnModificar.Click += btnModificar_Click;
            btnEliminar.BackColor = System.Drawing.ColorTranslator.FromHtml("#B23B3B");
            btnEliminar.ForeColor = System.Drawing.Color.White;
            btnEliminar.FlatStyle = FlatStyle.Flat;
            btnEliminar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnEliminar.Margin = new Padding(8, 5, 8, 5);
            btnEliminar.Name = "btnEliminar";
            btnEliminar.Size = new Size(130, 40);
            btnEliminar.TabIndex = 9;
            btnEliminar.Tag = "Eliminar";
            btnEliminar.Text = "Eliminar";
            btnEliminar.UseVisualStyleBackColor = false;
            btnEliminar.Click += btnEliminar_Click;
            btnGrabar.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            btnGrabar.ForeColor = System.Drawing.Color.White;
            btnGrabar.FlatStyle = FlatStyle.Flat;
            btnGrabar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnGrabar.Margin = new Padding(8, 5, 8, 5);
            btnGrabar.Name = "btnGrabar";
            btnGrabar.Size = new Size(120, 40);
            btnGrabar.TabIndex = 10;
            btnGrabar.Tag = "Grabar";
            btnGrabar.Text = "Grabar";
            btnGrabar.UseVisualStyleBackColor = false;
            btnGrabar.Visible = false;
            btnGrabar.Click += btnGrabar_Click;
            btnCancelar.BackColor = System.Drawing.ColorTranslator.FromHtml("#2D4D3A");
            btnCancelar.ForeColor = System.Drawing.Color.White;
            btnCancelar.FlatStyle = FlatStyle.Flat;
            btnCancelar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnCancelar.Margin = new Padding(8, 5, 8, 5);
            btnCancelar.Name = "btnCancelar";
            btnCancelar.Size = new Size(130, 40);
            btnCancelar.TabIndex = 11;
            btnCancelar.Tag = "Cancelar";
            btnCancelar.Text = "Cancelar";
            btnCancelar.UseVisualStyleBackColor = false;
            btnCancelar.Visible = false;
            btnCancelar.Click += btnCancelar_Click;
            btnToggleEliminados.BackColor = System.Drawing.ColorTranslator.FromHtml("#2D4D3A");
            btnToggleEliminados.ForeColor = System.Drawing.Color.White;
            btnToggleEliminados.FlatStyle = FlatStyle.Flat;
            btnToggleEliminados.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            btnToggleEliminados.Margin = new Padding(8, 5, 8, 5);
            btnToggleEliminados.Name = "btnToggleEliminados";
            btnToggleEliminados.Size = new Size(250, 40);
            btnToggleEliminados.TabIndex = 12;
            btnToggleEliminados.Tag = "MostrarEliminados";
            btnToggleEliminados.Text = "Mostrar eliminados";
            btnToggleEliminados.UseVisualStyleBackColor = false;
            btnToggleEliminados.Click += btnToggleEliminados_Click;
            pnlInputs.Controls.Add(lblNombreCompleto);
            pnlInputs.Controls.Add(txtNombreCompleto);
            pnlInputs.Controls.Add(lblDireccion);
            pnlInputs.Controls.Add(txtDireccion);
            pnlInputs.Controls.Add(lblTelefono);
            pnlInputs.Controls.Add(txtTelefono);
            pnlInputs.Controls.Add(lblEmail);
            pnlInputs.Controls.Add(txtEmail);
            pnlInputs.Controls.Add(lblZona);
            pnlInputs.Controls.Add(cbZona);
            pnlInputs.Controls.Add(chkActivo);
            pnlBotones.Controls.Add(btnAgregar);
            pnlBotones.Controls.Add(btnModificar);
            pnlBotones.Controls.Add(btnEliminar);
            pnlBotones.Controls.Add(btnGrabar);
            pnlBotones.Controls.Add(btnCancelar);
            pnlBotones.Controls.Add(btnToggleEliminados);
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1150, 750);
            Controls.Add(dgvClientes);
            Controls.Add(pnlBotones);
            Controls.Add(pnlInputs);
            Font = new Font("Segoe UI", 10F);
            MinimumSize = new Size(1000, 650);
            Name = "FrmClientes";
            StartPosition = FormStartPosition.CenterScreen;
            WindowState = FormWindowState.Maximized;
            Tag = "TituloClientes";
            Text = "Gestión de Clientes";
            Load += FrmClientes_Load;
            ((System.ComponentModel.ISupportInitialize)dgvClientes).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        private Label lblNombreCompleto;
        private Label lblDireccion;
        private Label lblTelefono;
        private Label lblEmail;
        private Label lblZona;
        private FlowLayoutPanel pnlInputs;
        private FlowLayoutPanel pnlBotones;
    }
}
