namespace UI
{
    partial class FrmLogin
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel tlpOuter;
        private System.Windows.Forms.Panel pnlCenter;
        private System.Windows.Forms.TableLayoutPanel tlpInner;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.TableLayoutPanel tlpFields;
        private System.Windows.Forms.Label lblIdioma;
        private System.Windows.Forms.ComboBox cbIdiomas;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.TextBox txtUsuario;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Button btnLogin;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tlpOuter = new System.Windows.Forms.TableLayoutPanel();
            this.pnlCenter = new System.Windows.Forms.Panel();
            this.tlpInner = new System.Windows.Forms.TableLayoutPanel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.tlpFields = new System.Windows.Forms.TableLayoutPanel();
            this.lblIdioma = new System.Windows.Forms.Label();
            this.cbIdiomas = new System.Windows.Forms.ComboBox();
            this.lblUsuario = new System.Windows.Forms.Label();
            this.txtUsuario = new System.Windows.Forms.TextBox();
            this.lblPassword = new System.Windows.Forms.Label();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.btnLogin = new System.Windows.Forms.Button();
            this.tlpOuter.SuspendLayout();
            this.pnlCenter.SuspendLayout();
            this.tlpInner.SuspendLayout();
            this.tlpFields.SuspendLayout();
            this.SuspendLayout();
            this.tlpOuter.ColumnCount = 3;
            this.tlpOuter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpOuter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpOuter.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpOuter.RowCount = 3;
            this.tlpOuter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpOuter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpOuter.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpOuter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpOuter.Name = "tlpOuter";
            this.tlpOuter.Controls.Add(this.pnlCenter, 1, 1);
            this.pnlCenter.AutoSize = true;
            this.pnlCenter.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.pnlCenter.Padding = new System.Windows.Forms.Padding(60, 40, 60, 40);
            this.pnlCenter.MinimumSize = new System.Drawing.Size(420, 0);
            this.pnlCenter.BackColor = System.Drawing.Color.FromArgb(250, 250, 250);
            this.pnlCenter.Controls.Add(this.tlpInner);
            this.pnlCenter.Name = "pnlCenter";
            this.tlpInner.AutoSize = true;
            this.tlpInner.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tlpInner.ColumnCount = 1;
            this.tlpInner.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpInner.RowCount = 3;
            this.tlpInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpInner.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpInner.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpInner.Name = "tlpInner";
            this.tlpInner.Controls.Add(this.lblTitulo, 0, 0);
            this.tlpInner.Controls.Add(this.tlpFields, 0, 1);
            this.tlpInner.Controls.Add(this.btnLogin, 0, 2);
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblTitulo.ForeColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            this.lblTitulo.Text = "Gestión de Bebidas";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblTitulo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 30);
            this.lblTitulo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lblTitulo.Name = "lblTitulo";
            this.tlpFields.AutoSize = true;
            this.tlpFields.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tlpFields.ColumnCount = 2;
            this.tlpFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 110F));
            this.tlpFields.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFields.RowCount = 3;
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.AutoSize));
            this.tlpFields.Margin = new System.Windows.Forms.Padding(0, 0, 0, 25);
            this.tlpFields.Name = "tlpFields";
            this.lblIdioma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lblIdioma.AutoSize = true;
            this.lblIdioma.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblIdioma.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblIdioma.Text = "Idioma:";
            this.lblIdioma.Tag = "lblIdioma";
            this.lblIdioma.Name = "lblIdioma";
            this.lblIdioma.Margin = new System.Windows.Forms.Padding(0, 0, 10, 15);
            this.tlpFields.Controls.Add(this.lblIdioma, 0, 0);
            this.cbIdiomas.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbIdiomas.FormattingEnabled = true;
            this.cbIdiomas.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.cbIdiomas.Name = "cbIdiomas";
            this.cbIdiomas.Size = new System.Drawing.Size(280, 25);
            this.cbIdiomas.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.cbIdiomas.SelectedIndexChanged += new System.EventHandler(this.cbIdiomas_SelectedIndexChanged);
            this.tlpFields.Controls.Add(this.cbIdiomas, 1, 0);
            this.lblUsuario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lblUsuario.AutoSize = true;
            this.lblUsuario.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblUsuario.Text = "Usuario:";
            this.lblUsuario.Tag = "lblUsuario";
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.Margin = new System.Windows.Forms.Padding(0, 0, 10, 15);
            this.tlpFields.Controls.Add(this.lblUsuario, 0, 1);
            this.txtUsuario.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtUsuario.Name = "txtUsuario";
            this.txtUsuario.Size = new System.Drawing.Size(280, 25);
            this.txtUsuario.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.tlpFields.Controls.Add(this.txtUsuario, 1, 1);
            this.lblPassword.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lblPassword.AutoSize = true;
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblPassword.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPassword.Text = "Contraseña:";
            this.lblPassword.Tag = "lblPassword";
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Margin = new System.Windows.Forms.Padding(0, 0, 10, 0);
            this.tlpFields.Controls.Add(this.lblPassword, 0, 2);
            this.txtPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(280, 25);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtPassword.UseSystemPasswordChar = true;
            this.tlpFields.Controls.Add(this.txtPassword, 1, 2);
            this.btnLogin.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnLogin.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.Size = new System.Drawing.Size(200, 45);
            this.btnLogin.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            this.btnLogin.ForeColor = System.Drawing.Color.White;
            this.btnLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogin.FlatAppearance.BorderSize = 0;
            this.btnLogin.Text = "Iniciar Sesión";
            this.btnLogin.Tag = "btnLogin";
            this.btnLogin.UseVisualStyleBackColor = false;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(240, 242, 245);
            this.ClientSize = new System.Drawing.Size(820, 560);
            this.MinimumSize = new System.Drawing.Size(640, 480);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login - Gestión de Bebidas";
            this.Tag = "FrmLogin";
            this.AcceptButton = this.btnLogin;
            this.Load += new System.EventHandler(this.FrmLogin_Load);
            this.Name = "FrmLogin";
            this.Controls.Add(this.tlpOuter);
            this.tlpOuter.ResumeLayout(false);
            this.tlpOuter.PerformLayout();
            this.pnlCenter.ResumeLayout(false);
            this.pnlCenter.PerformLayout();
            this.tlpInner.ResumeLayout(false);
            this.tlpInner.PerformLayout();
            this.tlpFields.ResumeLayout(false);
            this.tlpFields.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
