namespace UI
{
    partial class FrmProductos
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.DataGridView dgvProductos;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.ComboBox cbCategoria;
        private System.Windows.Forms.TextBox txtLitrosPorUnidad;
        private System.Windows.Forms.TextBox txtStock;
        private System.Windows.Forms.TextBox txtPrecio;
        private System.Windows.Forms.Button btnAgregar;
        private System.Windows.Forms.Button btnModificar;
        private System.Windows.Forms.Button btnEliminar;
        private System.Windows.Forms.Button btnGrabar;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Button btnToggleEliminados;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            dgvProductos = new DataGridView();
            txtNombre = new TextBox();
            cbCategoria = new ComboBox();
            txtLitrosPorUnidad = new TextBox();
            txtStock = new TextBox();
            txtPrecio = new TextBox();
            txtLote = new TextBox();
            dtpFechaIngreso = new DateTimePicker();
            dtpFechaVencimiento = new DateTimePicker();
            lblLote = new Label();
            lblFechaIngreso = new Label();
            lblFechaVencimiento = new Label();
            btnVerLotes = new Button();
            btnAgregarStock = new Button();
            btnAgregar = new Button();
            btnModificar = new Button();
            btnEliminar = new Button();
            btnGrabar = new Button();
            btnCancelar = new Button();
            btnToggleEliminados = new Button();
            lblNombre = new Label();
            lblCategoria = new Label();
            lblLitrosPorUnidad = new Label();
            lblStock = new Label();
            lblPrecio = new Label();
            pnlInputs = new FlowLayoutPanel();
            pnlBotones = new FlowLayoutPanel();
            ((System.ComponentModel.ISupportInitialize)dgvProductos).BeginInit();
            SuspendLayout();
            dgvProductos.AllowUserToAddRows = false;
            dgvProductos.AllowUserToDeleteRows = false;
            dgvProductos.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvProductos.Dock = DockStyle.Fill;
            dgvProductos.MultiSelect = false;
            dgvProductos.Name = "dgvProductos";
            dgvProductos.ReadOnly = true;
            dgvProductos.RowHeadersWidth = 51;
            dgvProductos.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvProductos.TabIndex = 0;
            dgvProductos.CellClick += dgvProductos_CellClick;
            dgvProductos.SelectionChanged += dgvProductos_SelectionChanged;
            pnlInputs.AutoScroll = true;
            pnlInputs.AutoSize = true;
            pnlInputs.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlInputs.Dock = DockStyle.Top;
            pnlInputs.FlowDirection = FlowDirection.LeftToRight;
            pnlInputs.Location = new Point(0, 0);
            pnlInputs.Name = "pnlInputs";
            pnlInputs.Padding = new Padding(12, 10, 12, 10);
            pnlInputs.Size = new Size(1150, 160);
            pnlInputs.TabIndex = 20;
            pnlInputs.WrapContents = true;
            pnlBotones.AutoScroll = true;
            pnlBotones.AutoSize = true;
            pnlBotones.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlBotones.Dock = DockStyle.Top;
            pnlBotones.FlowDirection = FlowDirection.LeftToRight;
            pnlBotones.Location = new Point(0, 160);
            pnlBotones.Name = "pnlBotones";
            pnlBotones.Padding = new Padding(12, 5, 12, 10);
            pnlBotones.Size = new Size(1150, 60);
            pnlBotones.TabIndex = 21;
            pnlBotones.WrapContents = true;
            lblNombre.AutoSize = true;
            lblNombre.Margin = new Padding(8, 0, 8, 0);
            lblNombre.Name = "lblNombre";
            lblNombre.Size = new Size(77, 23);
            lblNombre.TabIndex = 22;
            lblNombre.Tag = "Nombre";
            lblNombre.Text = "Nombre:";
            txtNombre.Margin = new Padding(4, 0, 20, 10);
            txtNombre.Name = "txtNombre";
            txtNombre.PlaceholderText = "Nombre del producto";
            txtNombre.Size = new Size(230, 30);
            txtNombre.TabIndex = 1;
            lblCategoria.AutoSize = true;
            lblCategoria.Margin = new Padding(8, 0, 8, 0);
            lblCategoria.Name = "lblCategoria";
            lblCategoria.Size = new Size(90, 23);
            lblCategoria.TabIndex = 23;
            lblCategoria.Tag = "Categoria";
            lblCategoria.Text = "Categoría:";
            cbCategoria.DropDownStyle = ComboBoxStyle.DropDownList;
            cbCategoria.Margin = new Padding(4, 0, 20, 10);
            cbCategoria.Name = "cbCategoria";
            cbCategoria.Size = new Size(170, 31);
            cbCategoria.TabIndex = 2;
            lblLitrosPorUnidad.AutoSize = true;
            lblLitrosPorUnidad.Margin = new Padding(8, 0, 8, 0);
            lblLitrosPorUnidad.Name = "lblLitrosPorUnidad";
            lblLitrosPorUnidad.Size = new Size(62, 23);
            lblLitrosPorUnidad.TabIndex = 24;
            lblLitrosPorUnidad.Tag = "Litros";
            lblLitrosPorUnidad.Text = "Litros:";
            txtLitrosPorUnidad.Margin = new Padding(4, 0, 20, 10);
            txtLitrosPorUnidad.Name = "txtLitrosPorUnidad";
            txtLitrosPorUnidad.PlaceholderText = "Capacidad (litros)";
            txtLitrosPorUnidad.Size = new Size(140, 30);
            txtLitrosPorUnidad.TabIndex = 3;
            lblStock.AutoSize = true;
            lblStock.Margin = new Padding(8, 10, 8, 0);
            lblStock.Name = "lblStock";
            lblStock.Size = new Size(58, 23);
            lblStock.TabIndex = 25;
            lblStock.Tag = "Stock";
            lblStock.Text = "Stock:";
            txtStock.Margin = new Padding(4, 5, 20, 10);
            txtStock.Name = "txtStock";
            txtStock.PlaceholderText = "Stock";
            txtStock.ReadOnly = true;
            txtStock.Size = new Size(115, 30);
            txtStock.TabIndex = 4;
            lblPrecio.AutoSize = true;
            lblPrecio.Margin = new Padding(8, 10, 8, 0);
            lblPrecio.Name = "lblPrecio";
            lblPrecio.Size = new Size(63, 23);
            lblPrecio.TabIndex = 26;
            lblPrecio.Tag = "Precio";
            lblPrecio.Text = "Precio:";
            txtPrecio.Margin = new Padding(4, 5, 20, 10);
            txtPrecio.Name = "txtPrecio";
            txtPrecio.PlaceholderText = "Precio";
            txtPrecio.Size = new Size(115, 30);
            txtPrecio.TabIndex = 5;
            lblLote.AutoSize = true;
            lblLote.Margin = new Padding(8, 10, 8, 0);
            lblLote.Name = "lblLote";
            lblLote.Size = new Size(47, 23);
            lblLote.TabIndex = 15;
            lblLote.Tag = "Lote";
            lblLote.Text = "Lote:";
            txtLote.Margin = new Padding(4, 5, 20, 10);
            txtLote.Name = "txtLote";
            txtLote.Size = new Size(100, 30);
            txtLote.TabIndex = 6;
            lblFechaIngreso.AutoSize = true;
            lblFechaIngreso.Margin = new Padding(8, 10, 8, 0);
            lblFechaIngreso.Name = "lblFechaIngreso";
            lblFechaIngreso.Size = new Size(88, 23);
            lblFechaIngreso.TabIndex = 14;
            lblFechaIngreso.Tag = "FechaIngreso";
            lblFechaIngreso.Text = "F. Ingreso:";
            dtpFechaIngreso.Format = DateTimePickerFormat.Short;
            dtpFechaIngreso.Margin = new Padding(4, 5, 20, 10);
            dtpFechaIngreso.Name = "dtpFechaIngreso";
            dtpFechaIngreso.Size = new Size(140, 30);
            dtpFechaIngreso.TabIndex = 7;
            lblFechaVencimiento.AutoSize = true;
            lblFechaVencimiento.Margin = new Padding(8, 10, 8, 0);
            lblFechaVencimiento.Name = "lblFechaVencimiento";
            lblFechaVencimiento.Size = new Size(91, 23);
            lblFechaVencimiento.TabIndex = 13;
            lblFechaVencimiento.Tag = "FechaVencimiento";
            lblFechaVencimiento.Text = "F. Vencim.:";
            dtpFechaVencimiento.Format = DateTimePickerFormat.Short;
            dtpFechaVencimiento.Margin = new Padding(4, 5, 20, 10);
            dtpFechaVencimiento.Name = "dtpFechaVencimiento";
            dtpFechaVencimiento.Size = new Size(140, 30);
            dtpFechaVencimiento.TabIndex = 8;
            btnAgregar.Margin = new Padding(8, 5, 8, 5);
            btnAgregar.Name = "btnAgregar";
            btnAgregar.Size = new Size(120, 40);
            btnAgregar.TabIndex = 6;
            btnAgregar.Tag = "Agregar";
            btnAgregar.Text = "Agregar";
            btnAgregar.UseVisualStyleBackColor = true;
            btnAgregar.Click += btnAgregar_Click;
            btnModificar.Enabled = false;
            btnModificar.Margin = new Padding(8, 5, 8, 5);
            btnModificar.Name = "btnModificar";
            btnModificar.Size = new Size(130, 40);
            btnModificar.TabIndex = 7;
            btnModificar.Tag = "Modificar";
            btnModificar.Text = "Modificar";
            btnModificar.UseVisualStyleBackColor = true;
            btnModificar.Click += btnModificar_Click;
            btnEliminar.Margin = new Padding(8, 5, 8, 5);
            btnEliminar.Name = "btnEliminar";
            btnEliminar.Size = new Size(120, 40);
            btnEliminar.TabIndex = 8;
            btnEliminar.Tag = "Eliminar";
            btnEliminar.Text = "Eliminar";
            btnEliminar.UseVisualStyleBackColor = true;
            btnEliminar.Click += btnEliminar_Click;
            btnGrabar.Margin = new Padding(8, 5, 8, 5);
            btnGrabar.Name = "btnGrabar";
            btnGrabar.Size = new Size(115, 40);
            btnGrabar.TabIndex = 9;
            btnGrabar.Tag = "Grabar";
            btnGrabar.Text = "Grabar";
            btnGrabar.UseVisualStyleBackColor = true;
            btnGrabar.Visible = false;
            btnGrabar.Click += btnGrabar_Click;
            btnCancelar.Margin = new Padding(8, 5, 8, 5);
            btnCancelar.Name = "btnCancelar";
            btnCancelar.Size = new Size(125, 40);
            btnCancelar.TabIndex = 10;
            btnCancelar.Tag = "Cancelar";
            btnCancelar.Text = "Cancelar";
            btnCancelar.UseVisualStyleBackColor = true;
            btnCancelar.Visible = false;
            btnCancelar.Click += btnCancelar_Click;
            btnAgregarStock.Margin = new Padding(8, 5, 8, 5);
            btnAgregarStock.Name = "btnAgregarStock";
            btnAgregarStock.Size = new Size(180, 40);
            btnAgregarStock.TabIndex = 13;
            btnAgregarStock.Text = "Agregar Unidades";
            btnAgregarStock.UseVisualStyleBackColor = true;
            btnAgregarStock.Visible = false;
            btnAgregarStock.Click += btnAgregarUnidades_Click;
            btnVerLotes.Margin = new Padding(8, 5, 8, 5);
            btnVerLotes.Name = "btnVerLotes";
            btnVerLotes.Size = new Size(140, 40);
            btnVerLotes.TabIndex = 12;
            btnVerLotes.Text = "Ver Lotes";
            btnVerLotes.Click += btnVerLotes_Click;
            btnToggleEliminados.Margin = new Padding(8, 5, 8, 5);
            btnToggleEliminados.Name = "btnToggleEliminados";
            btnToggleEliminados.Size = new Size(200, 40);
            btnToggleEliminados.TabIndex = 11;
            btnToggleEliminados.Tag = "MostrarEliminados";
            btnToggleEliminados.Text = "Mostrar eliminados";
            btnToggleEliminados.UseVisualStyleBackColor = true;
            btnToggleEliminados.Click += btnToggleEliminados_Click;
            pnlInputs.Controls.Add(lblNombre);
            pnlInputs.Controls.Add(txtNombre);
            pnlInputs.Controls.Add(lblCategoria);
            pnlInputs.Controls.Add(cbCategoria);
            pnlInputs.Controls.Add(lblLitrosPorUnidad);
            pnlInputs.Controls.Add(txtLitrosPorUnidad);
            pnlInputs.Controls.Add(lblStock);
            pnlInputs.Controls.Add(txtStock);
            pnlInputs.Controls.Add(lblPrecio);
            pnlInputs.Controls.Add(txtPrecio);
            pnlInputs.Controls.Add(lblLote);
            pnlInputs.Controls.Add(txtLote);
            pnlInputs.Controls.Add(lblFechaIngreso);
            pnlInputs.Controls.Add(dtpFechaIngreso);
            pnlInputs.Controls.Add(lblFechaVencimiento);
            pnlInputs.Controls.Add(dtpFechaVencimiento);
            pnlBotones.Controls.Add(btnAgregar);
            pnlBotones.Controls.Add(btnModificar);
            pnlBotones.Controls.Add(btnEliminar);
            pnlBotones.Controls.Add(btnGrabar);
            pnlBotones.Controls.Add(btnCancelar);
            pnlBotones.Controls.Add(btnAgregarStock);
            pnlBotones.Controls.Add(btnVerLotes);
            pnlBotones.Controls.Add(btnToggleEliminados);
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1150, 750);
            Controls.Add(dgvProductos);
            Controls.Add(pnlBotones);
            Controls.Add(pnlInputs);
            Font = new Font("Segoe UI", 10F);
            MinimumSize = new Size(1100, 700);
            Name = "FrmProductos";
            StartPosition = FormStartPosition.CenterScreen;
            WindowState = FormWindowState.Maximized;
            Text = "Gestión de Productos";
            Load += FrmProductos_Load_1;
            ((System.ComponentModel.ISupportInitialize)dgvProductos).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        private TextBox txtLote;
        private DateTimePicker dtpFechaIngreso;
        private DateTimePicker dtpFechaVencimiento;
        private Label lblLote;
        private Label lblFechaIngreso;
        private Label lblFechaVencimiento;
        private Button btnVerLotes;
        private Button btnAgregarStock;
        private Label lblNombre;
        private Label lblCategoria;
        private Label lblLitrosPorUnidad;
        private Label lblStock;
        private Label lblPrecio;
        private FlowLayoutPanel pnlInputs;
        private FlowLayoutPanel pnlBotones;
    }
}
