namespace UI
{
    partial class FrmPermisos
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TabControl tabControl;
        private System.Windows.Forms.TabPage tabGestionar;
        private System.Windows.Forms.TabPage tabAsignar;
        private System.Windows.Forms.ListBox lstCompuestos;
        private System.Windows.Forms.TextBox txtGrupoNombre;
        private System.Windows.Forms.CheckedListBox clbSimplesParaGrupo;
        private System.Windows.Forms.Button btnCrearGrupo;
        private System.Windows.Forms.ListBox lstUsuarios;
        private System.Windows.Forms.CheckedListBox clbGruposAsignar;
        private System.Windows.Forms.Button btnGuardarAsignacion;
        private System.Windows.Forms.TreeView tvJerarquiaUsuario;
        private System.Windows.Forms.Label lblJerarquiaUsuario;
        private System.Windows.Forms.Label lblCompuestos;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.Label lblSeleccionPermisos;
        private System.Windows.Forms.TreeView tvPermisos;
        private System.Windows.Forms.TreeView tvJerarquia;
        private System.Windows.Forms.Label lblJerarquia;
        private System.Windows.Forms.Button btnGuardarGrupo;
        private System.Windows.Forms.Button btnEliminarGrupo;
        private void InitializeComponent()
        {
            tabControl = new TabControl();
            tabGestionar = new TabPage();
            lblCompuestos = new Label();
            lstCompuestos = new ListBox();
            lblSeleccionPermisos = new Label();
            clbSimplesParaGrupo = new CheckedListBox();
            tvPermisos = new TreeView();
            tvJerarquia = new TreeView();
            lblJerarquia = new Label();
            btnGuardarGrupo = new Button();
            btnEliminarGrupo = new Button();
            txtGrupoNombre = new TextBox();
            btnCrearGrupo = new Button();
            tabAsignar = new TabPage();
            lblUsuario = new Label();
            lstUsuarios = new ListBox();
            clbGruposAsignar = new CheckedListBox();
            btnGuardarAsignacion = new Button();
            tvJerarquiaUsuario = new TreeView();
            lblJerarquiaUsuario = new Label();
            tabControl.SuspendLayout();
            tabGestionar.SuspendLayout();
            tabAsignar.SuspendLayout();
            SuspendLayout();
            tabControl.Controls.Add(tabGestionar);
            tabControl.Controls.Add(tabAsignar);
            tabControl.Dock = DockStyle.Fill;
            tabControl.Location = new Point(0, 0);
            tabControl.Name = "tabControl";
            tabControl.SelectedIndex = 0;
            tabControl.Size = new Size(1553, 798);
            tabControl.TabIndex = 0;
            tabGestionar.Controls.Add(lblCompuestos);
            tabGestionar.Controls.Add(lstCompuestos);
            tabGestionar.Controls.Add(lblSeleccionPermisos);
            tabGestionar.Controls.Add(clbSimplesParaGrupo);
            tabGestionar.Controls.Add(tvPermisos);
            tabGestionar.Controls.Add(tvJerarquia);
            tabGestionar.Controls.Add(lblJerarquia);
            tabGestionar.Controls.Add(btnGuardarGrupo);
            tabGestionar.Controls.Add(btnEliminarGrupo);
            tabGestionar.Controls.Add(txtGrupoNombre);
            tabGestionar.Controls.Add(btnCrearGrupo);
            tabGestionar.Location = new Point(4, 32);
            tabGestionar.Name = "tabGestionar";
            tabGestionar.Size = new Size(1545, 762);
            tabGestionar.TabIndex = 0;
            tabGestionar.Tag = "Gestionar";
            tabGestionar.Text = "Gestionar";
            lblCompuestos.Location = new Point(70, 19);
            lblCompuestos.Name = "lblCompuestos";
            lblCompuestos.Size = new Size(216, 23);
            lblCompuestos.TabIndex = 4;
            lblCompuestos.Tag = "PermisosCompuestos";
            lblCompuestos.Text = "Permisos Compuestos";
            lstCompuestos.ItemHeight = 23;
            lstCompuestos.Location = new Point(23, 45);
            lstCompuestos.Name = "lstCompuestos";
            lstCompuestos.Size = new Size(310, 579);
            lstCompuestos.TabIndex = 5;
            lstCompuestos.SelectedIndexChanged += lstCompuestos_SelectedIndexChanged;
            lblSeleccionPermisos.Location = new Point(634, 19);
            lblSeleccionPermisos.Name = "lblSeleccionPermisos";
            lblSeleccionPermisos.Size = new Size(100, 23);
            lblSeleccionPermisos.TabIndex = 6;
            lblSeleccionPermisos.Tag = "SeleccionarSimples";
            lblSeleccionPermisos.Text = "Catálogo de permisos";
            clbSimplesParaGrupo.CheckOnClick = true;
            clbSimplesParaGrupo.Location = new Point(808, 45);
            clbSimplesParaGrupo.Name = "clbSimplesParaGrupo";
            clbSimplesParaGrupo.Size = new Size(360, 429);
            clbSimplesParaGrupo.TabIndex = 7;
            clbSimplesParaGrupo.ItemCheck += clbSimplesParaGrupo_ItemCheck;
            tvPermisos.CheckBoxes = true;
            tvPermisos.Location = new Point(368, 45);
            tvPermisos.Name = "tvPermisos";
            tvPermisos.Size = new Size(430, 579);
            tvPermisos.TabIndex = 10;
            tvPermisos.AfterCheck += tvPermisos_AfterCheck;
            lblJerarquia.Location = new Point(1180, 19);
            lblJerarquia.Name = "lblJerarquia";
            lblJerarquia.Size = new Size(150, 23);
            lblJerarquia.TabIndex = 13;
            lblJerarquia.Text = "Jerarquía del grupo";
            tvJerarquia.Location = new Point(1180, 45);
            tvJerarquia.Name = "tvJerarquia";
            tvJerarquia.Size = new Size(340, 579);
            tvJerarquia.TabIndex = 14;
            btnGuardarGrupo.Location = new Point(368, 640);
            btnGuardarGrupo.Name = "btnGuardarGrupo";
            btnGuardarGrupo.Size = new Size(180, 32);
            btnGuardarGrupo.TabIndex = 11;
            btnGuardarGrupo.Tag = "GuardarAsignacion";
            btnGuardarGrupo.Text = "Guardar Cambios";
            btnGuardarGrupo.Click += btnGuardarGrupo_Click;
            btnEliminarGrupo.Location = new Point(213, 690);
            btnEliminarGrupo.Name = "btnEliminarGrupo";
            btnEliminarGrupo.Size = new Size(120, 30);
            btnEliminarGrupo.TabIndex = 12;
            btnEliminarGrupo.Tag = "EliminarGrupo";
            btnEliminarGrupo.Text = "Eliminar Grupo";
            btnEliminarGrupo.Click += btnEliminarGrupo_Click;
            txtGrupoNombre.Location = new Point(23, 656);
            txtGrupoNombre.Name = "txtGrupoNombre";
            txtGrupoNombre.Size = new Size(180, 30);
            txtGrupoNombre.TabIndex = 8;
            btnCrearGrupo.Location = new Point(213, 654);
            btnCrearGrupo.Name = "btnCrearGrupo";
            btnCrearGrupo.Size = new Size(120, 30);
            btnCrearGrupo.TabIndex = 9;
            btnCrearGrupo.Tag = "CrearGrupo";
            btnCrearGrupo.Text = "Crear Grupo";
            btnCrearGrupo.Click += btnCrearGrupo_Click;
            tabAsignar.Controls.Add(lblUsuario);
            tabAsignar.Controls.Add(lstUsuarios);
            tabAsignar.Controls.Add(clbGruposAsignar);
            tabAsignar.Controls.Add(btnGuardarAsignacion);
            tabAsignar.Controls.Add(tvJerarquiaUsuario);
            tabAsignar.Controls.Add(lblJerarquiaUsuario);
            tabAsignar.Location = new Point(4, 32);
            tabAsignar.Name = "tabAsignar";
            tabAsignar.Size = new Size(1545, 762);
            tabAsignar.TabIndex = 1;
            tabAsignar.Tag = "Asignar";
            tabAsignar.Text = "Asignar";
            lblUsuario.Location = new Point(20, 20);
            lblUsuario.Name = "lblUsuario";
            lblUsuario.Size = new Size(100, 23);
            lblUsuario.TabIndex = 0;
            lblUsuario.Tag = "Usuario";
            lblUsuario.Text = "Usuario";
            lstUsuarios.FormattingEnabled = true;
            lstUsuarios.ItemHeight = 23;
            lstUsuarios.Location = new Point(20, 60);
            lstUsuarios.Name = "lstUsuarios";
            lstUsuarios.Size = new Size(300, 372);
            lstUsuarios.TabIndex = 1;
            lstUsuarios.SelectedIndexChanged += lstUsuarios_SelectedIndexChanged;
            clbGruposAsignar.CheckOnClick = true;
            clbGruposAsignar.Location = new Point(340, 60);
            clbGruposAsignar.Name = "clbGruposAsignar";
            clbGruposAsignar.Size = new Size(420, 379);
            clbGruposAsignar.TabIndex = 2;
            btnGuardarAsignacion.Location = new Point(20, 460);
            btnGuardarAsignacion.Name = "btnGuardarAsignacion";
            btnGuardarAsignacion.Size = new Size(180, 32);
            btnGuardarAsignacion.TabIndex = 3;
            btnGuardarAsignacion.Tag = "GuardarAsignacion";
            btnGuardarAsignacion.Text = "Guardar Asignación";
            btnGuardarAsignacion.Click += btnGuardarAsignacion_Click;
            lblJerarquiaUsuario.Location = new Point(780, 20);
            lblJerarquiaUsuario.Name = "lblJerarquiaUsuario";
            lblJerarquiaUsuario.Size = new Size(220, 23);
            lblJerarquiaUsuario.TabIndex = 4;
            lblJerarquiaUsuario.Text = "Jerarquía de permisos (usuario)";
            tvJerarquiaUsuario.Location = new Point(780, 60);
            tvJerarquiaUsuario.Name = "tvJerarquiaUsuario";
            tvJerarquiaUsuario.Size = new Size(740, 679);
            tvJerarquiaUsuario.TabIndex = 5;
            ClientSize = new Size(1553, 798);
            Controls.Add(tabControl);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmPermisos";
            Text = "Permisos";
            tabControl.ResumeLayout(false);
            tabGestionar.ResumeLayout(false);
            tabGestionar.PerformLayout();
            tabAsignar.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
