namespace UI
{
    partial class FrmReportes
    {
        private System.ComponentModel.IContainer components = null;
        private ComboBox cbTipoReporte;
        private ComboBox cbZona;
        private ComboBox cbProducto;
        private ComboBox cbPeriodo;
        private ComboBox cbCategoria;
        private ComboBox cbEstado;
        private ComboBox cbAgrupar;
        private NumericUpDown numUmbral;
        private DateTimePicker dtpFechaDesde;
        private DateTimePicker dtpFechaHasta;
        private CheckBox chkFechaDesde;
        private CheckBox chkFechaHasta;
        private Button btnGenerarReporte;
        private Button btnLimpiar;
        private Button btnExportar;
        private Label lblEstado;
        private Label lblContexto;
        private Label lblComparacion;
        private Label lblVacio;
        private FlowLayoutPanel filtrosVentas;
        private FlowLayoutPanel filtrosStock;
        private Reportes.ReporteGrafico graficoEvolucion;
        private Reportes.ReporteGrafico graficoRanking;
        private DataGridView dgvReporte;
        private DataGridView dgvAnalisis;
        private Panel panelFiltros;
        private TableLayoutPanel raiz;
        private Panel encabezado;
        private Label lblTitulo;
        private TableLayoutPanel filtros;
        private FlowLayoutPanel fila;
        private Label lblFiltro1;
        private Label lblFiltro2;
        private Label lblFiltro3;
        private Panel alternables;
        private Label lblFiltro4;
        private Label lblFiltro5;
        private Label lblFiltro6;
        private FlowLayoutPanel acciones;
        private TableLayoutPanel tarjetas;
        private Panel card0;
        private Label tituloIndicador0;
        private Label indicador0;
        private Panel card1;
        private Label tituloIndicador1;
        private Label indicador1;
        private Panel card2;
        private Label tituloIndicador2;
        private Label indicador2;
        private Panel card3;
        private Label tituloIndicador3;
        private Label indicador3;
        private TableLayoutPanel graficos;
        private TabControl tabs;
        private FlowLayoutPanel agrupar;
        private Label lblFiltro7;
        private TabPage detalle;
        private TabPage analisis;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            cbTipoReporte = new ComboBox();
            cbZona = new ComboBox();
            cbProducto = new ComboBox();
            cbPeriodo = new ComboBox();
            cbCategoria = new ComboBox();
            cbEstado = new ComboBox();
            cbAgrupar = new ComboBox();
            numUmbral = new NumericUpDown();
            dtpFechaDesde = new DateTimePicker();
            dtpFechaHasta = new DateTimePicker();
            chkFechaDesde = new CheckBox();
            chkFechaHasta = new CheckBox();
            btnGenerarReporte = new Button();
            btnLimpiar = new Button();
            btnExportar = new Button();
            lblEstado = new Label();
            lblContexto = new Label();
            lblComparacion = new Label();
            lblVacio = new Label();
            filtrosVentas = new FlowLayoutPanel();
            filtrosStock = new FlowLayoutPanel();
            lblFiltro4 = new Label();
            lblFiltro5 = new Label();
            lblFiltro6 = new Label();
            graficoEvolucion = new UI.Reportes.ReporteGrafico();
            graficoRanking = new UI.Reportes.ReporteGrafico();
            dgvReporte = new DataGridView();
            dgvAnalisis = new DataGridView();
            panelFiltros = new Panel();
            filtros = new TableLayoutPanel();
            fila = new FlowLayoutPanel();
            lblFiltro1 = new Label();
            lblFiltro2 = new Label();
            lblFiltro3 = new Label();
            alternables = new Panel();
            acciones = new FlowLayoutPanel();
            raiz = new TableLayoutPanel();
            encabezado = new Panel();
            lblTitulo = new Label();
            tarjetas = new TableLayoutPanel();
            card0 = new Panel();
            indicador0 = new Label();
            tituloIndicador0 = new Label();
            card1 = new Panel();
            indicador1 = new Label();
            tituloIndicador1 = new Label();
            card2 = new Panel();
            indicador2 = new Label();
            tituloIndicador2 = new Label();
            card3 = new Panel();
            indicador3 = new Label();
            tituloIndicador3 = new Label();
            graficos = new TableLayoutPanel();
            tabs = new TabControl();
            detalle = new TabPage();
            analisis = new TabPage();
            agrupar = new FlowLayoutPanel();
            lblFiltro7 = new Label();
            ((System.ComponentModel.ISupportInitialize)numUmbral).BeginInit();
            filtrosVentas.SuspendLayout();
            filtrosStock.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvReporte).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvAnalisis).BeginInit();
            panelFiltros.SuspendLayout();
            filtros.SuspendLayout();
            fila.SuspendLayout();
            alternables.SuspendLayout();
            acciones.SuspendLayout();
            raiz.SuspendLayout();
            encabezado.SuspendLayout();
            tarjetas.SuspendLayout();
            card0.SuspendLayout();
            card1.SuspendLayout();
            card2.SuspendLayout();
            card3.SuspendLayout();
            graficos.SuspendLayout();
            tabs.SuspendLayout();
            detalle.SuspendLayout();
            analisis.SuspendLayout();
            agrupar.SuspendLayout();
            SuspendLayout();
            cbTipoReporte.DropDownStyle = ComboBoxStyle.DropDownList;
            cbTipoReporte.Items.AddRange(new object[] { "Ventas", "Stock" });
            cbTipoReporte.Location = new Point(81, 4);
            cbTipoReporte.Margin = new Padding(3, 4, 12, 0);
            cbTipoReporte.Name = "cbTipoReporte";
            cbTipoReporte.Size = new Size(140, 31);
            cbTipoReporte.TabIndex = 1;
            cbZona.DropDownStyle = ComboBoxStyle.DropDownList;
            cbZona.Location = new Point(641, 4);
            cbZona.Margin = new Padding(3, 4, 12, 0);
            cbZona.Name = "cbZona";
            cbZona.Size = new Size(180, 31);
            cbZona.TabIndex = 5;
            cbProducto.DropDownStyle = ComboBoxStyle.DropDownList;
            cbProducto.Location = new Point(324, 4);
            cbProducto.Margin = new Padding(3, 4, 12, 0);
            cbProducto.Name = "cbProducto";
            cbProducto.Size = new Size(245, 31);
            cbProducto.TabIndex = 3;
            cbPeriodo.DropDownStyle = ComboBoxStyle.DropDownList;
            cbPeriodo.Items.AddRange(new object[] { "Este mes", "Hoy", "Mes anterior", "Personalizado", "Todo el historial" });
            cbPeriodo.Location = new Point(3, 4);
            cbPeriodo.Margin = new Padding(3, 4, 12, 0);
            cbPeriodo.Name = "cbPeriodo";
            cbPeriodo.Size = new Size(150, 31);
            cbPeriodo.TabIndex = 0;
            cbCategoria.DropDownStyle = ComboBoxStyle.DropDownList;
            cbCategoria.Location = new Point(95, 4);
            cbCategoria.Margin = new Padding(3, 4, 12, 0);
            cbCategoria.Name = "cbCategoria";
            cbCategoria.Size = new Size(180, 31);
            cbCategoria.TabIndex = 1;
            cbEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            cbEstado.Items.AddRange(new object[] { "Todos", "Sin stock", "Stock bajo", "Por vencer (30 días)", "Con lotes vencidos" });
            cbEstado.Location = new Point(359, 4);
            cbEstado.Margin = new Padding(3, 4, 12, 0);
            cbEstado.Name = "cbEstado";
            cbEstado.Size = new Size(205, 31);
            cbEstado.TabIndex = 3;
            cbAgrupar.DropDownStyle = ComboBoxStyle.DropDownList;
            cbAgrupar.Items.AddRange(new object[] { "Producto", "Vendedor", "Zona", "Cliente" });
            cbAgrupar.Location = new Point(114, 4);
            cbAgrupar.Margin = new Padding(3, 4, 12, 0);
            cbAgrupar.Name = "cbAgrupar";
            cbAgrupar.Size = new Size(220, 31);
            cbAgrupar.TabIndex = 1;
            numUmbral.Location = new Point(718, 4);
            numUmbral.Margin = new Padding(3, 4, 0, 0);
            numUmbral.Maximum = new decimal (new int[] { 1000000, 0, 0, 0 });
            numUmbral.Minimum = new decimal (new int[] { 1, 0, 0, 0 });
            numUmbral.Name = "numUmbral";
            numUmbral.Size = new Size(80, 30);
            numUmbral.TabIndex = 5;
            numUmbral.Value = new decimal (new int[] { 10, 0, 0, 0 });
            dtpFechaDesde.CustomFormat = "dd/MM/yyyy";
            dtpFechaDesde.Format = DateTimePickerFormat.Custom;
            dtpFechaDesde.Location = new Point(263, 4);
            dtpFechaDesde.Margin = new Padding(3, 4, 8, 0);
            dtpFechaDesde.Name = "dtpFechaDesde";
            dtpFechaDesde.Size = new Size(135, 30);
            dtpFechaDesde.TabIndex = 2;
            dtpFechaHasta.CustomFormat = "dd/MM/yyyy";
            dtpFechaHasta.Format = DateTimePickerFormat.Custom;
            dtpFechaHasta.Location = new Point(500, 4);
            dtpFechaHasta.Margin = new Padding(3, 4, 8, 0);
            dtpFechaHasta.Name = "dtpFechaHasta";
            dtpFechaHasta.Size = new Size(135, 30);
            dtpFechaHasta.TabIndex = 4;
            chkFechaDesde.AutoSize = true;
            chkFechaDesde.Location = new Point(177, 8);
            chkFechaDesde.Margin = new Padding(12, 8, 4, 0);
            chkFechaDesde.Name = "chkFechaDesde";
            chkFechaDesde.Size = new Size(79, 27);
            chkFechaDesde.TabIndex = 1;
            chkFechaDesde.Text = "Desde";
            chkFechaHasta.AutoSize = true;
            chkFechaHasta.Location = new Point(418, 8);
            chkFechaHasta.Margin = new Padding(12, 8, 4, 0);
            chkFechaHasta.Name = "chkFechaHasta";
            chkFechaHasta.Size = new Size(75, 27);
            chkFechaHasta.TabIndex = 3;
            chkFechaHasta.Text = "Hasta";
            btnGenerarReporte.FlatStyle = FlatStyle.Flat;
            btnGenerarReporte.Location = new Point(0, 2);
            btnGenerarReporte.Margin = new Padding(0, 2, 10, 2);
            btnGenerarReporte.Name = "btnGenerarReporte";
            btnGenerarReporte.Size = new Size(155, 36);
            btnGenerarReporte.TabIndex = 0;
            btnGenerarReporte.Tag = "GenerarReporte";
            btnGenerarReporte.Text = "Generar reporte";
            btnGenerarReporte.Click += btnGenerarReporte_Click_1;
            btnLimpiar.FlatStyle = FlatStyle.Flat;
            btnLimpiar.Location = new Point(165, 2);
            btnLimpiar.Margin = new Padding(0, 2, 10, 2);
            btnLimpiar.Name = "btnLimpiar";
            btnLimpiar.Size = new Size(155, 36);
            btnLimpiar.TabIndex = 1;
            btnLimpiar.Tag = "LimpiarFiltros";
            btnLimpiar.Text = "Restablecer";
            btnExportar.Enabled = false;
            btnExportar.FlatStyle = FlatStyle.Flat;
            btnExportar.Location = new Point(330, 2);
            btnExportar.Margin = new Padding(0, 2, 10, 2);
            btnExportar.Name = "btnExportar";
            btnExportar.Size = new Size(155, 36);
            btnExportar.TabIndex = 2;
            btnExportar.Text = "Exportar ▾";
            lblEstado.Dock = DockStyle.Fill;
            lblEstado.Location = new Point(25, 768);
            lblEstado.Name = "lblEstado";
            lblEstado.Size = new Size(1150, 30);
            lblEstado.TabIndex = 6;
            lblEstado.TextAlign = ContentAlignment.MiddleLeft;
            lblContexto.Dock = DockStyle.Bottom;
            lblContexto.ForeColor = Color.DimGray;
            lblContexto.Location = new Point(0, 38);
            lblContexto.Name = "lblContexto";
            lblContexto.Size = new Size(1150, 24);
            lblContexto.TabIndex = 1;
            lblComparacion.Dock = DockStyle.Fill;
            lblComparacion.Location = new Point(25, 340);
            lblComparacion.Name = "lblComparacion";
            lblComparacion.Size = new Size(1150, 38);
            lblComparacion.TabIndex = 3;
            lblComparacion.TextAlign = ContentAlignment.MiddleLeft;
            lblVacio.BackColor = Color.White;
            lblVacio.Dock = DockStyle.Fill;
            lblVacio.Location = new Point(0, 0);
            lblVacio.Name = "lblVacio";
            lblVacio.Size = new Size(1142, 158);
            lblVacio.TabIndex = 1;
            lblVacio.Text = "Seleccioná los filtros y generá el reporte.";
            lblVacio.TextAlign = ContentAlignment.MiddleCenter;
            filtrosVentas.AutoScroll = true;
            filtrosVentas.Controls.Add(cbPeriodo);
            filtrosVentas.Controls.Add(chkFechaDesde);
            filtrosVentas.Controls.Add(dtpFechaDesde);
            filtrosVentas.Controls.Add(chkFechaHasta);
            filtrosVentas.Controls.Add(dtpFechaHasta);
            filtrosVentas.Dock = DockStyle.Fill;
            filtrosVentas.Location = new Point(0, 0);
            filtrosVentas.Margin = new Padding(0);
            filtrosVentas.Name = "filtrosVentas";
            filtrosVentas.Size = new Size(1128, 38);
            filtrosVentas.TabIndex = 0;
            filtrosVentas.WrapContents = false;
            filtrosStock.AutoScroll = true;
            filtrosStock.Controls.Add(lblFiltro4);
            filtrosStock.Controls.Add(cbCategoria);
            filtrosStock.Controls.Add(lblFiltro5);
            filtrosStock.Controls.Add(cbEstado);
            filtrosStock.Controls.Add(lblFiltro6);
            filtrosStock.Controls.Add(numUmbral);
            filtrosStock.Dock = DockStyle.Fill;
            filtrosStock.Location = new Point(0, 0);
            filtrosStock.Margin = new Padding(0);
            filtrosStock.Name = "filtrosStock";
            filtrosStock.Size = new Size(1128, 38);
            filtrosStock.TabIndex = 1;
            filtrosStock.Visible = false;
            filtrosStock.WrapContents = false;
            lblFiltro4.AutoSize = true;
            lblFiltro4.Location = new Point(4, 8);
            lblFiltro4.Margin = new Padding(4, 8, 4, 0);
            lblFiltro4.Name = "lblFiltro4";
            lblFiltro4.Size = new Size(84, 23);
            lblFiltro4.TabIndex = 0;
            lblFiltro4.Text = "Categoría";
            lblFiltro5.AutoSize = true;
            lblFiltro5.Location = new Point(291, 8);
            lblFiltro5.Margin = new Padding(4, 8, 4, 0);
            lblFiltro5.Name = "lblFiltro5";
            lblFiltro5.Size = new Size(61, 23);
            lblFiltro5.TabIndex = 2;
            lblFiltro5.Text = "Estado";
            lblFiltro6.AutoSize = true;
            lblFiltro6.Location = new Point(580, 8);
            lblFiltro6.Margin = new Padding(4, 8, 4, 0);
            lblFiltro6.Name = "lblFiltro6";
            lblFiltro6.Size = new Size(131, 23);
            lblFiltro6.TabIndex = 4;
            lblFiltro6.Text = "Umbral bajo (≤)";
            graficoEvolucion.BackColor = Color.White;
            graficoEvolucion.Dock = DockStyle.Fill;
            graficoEvolucion.Location = new Point(3, 3);
            graficoEvolucion.Margin = new Padding(3, 3, 6, 8);
            graficoEvolucion.Name = "graficoEvolucion";
            graficoEvolucion.Size = new Size(566, 173);
            graficoEvolucion.TabIndex = 0;
            graficoRanking.BackColor = Color.White;
            graficoRanking.Dock = DockStyle.Fill;
            graficoRanking.Location = new Point(578, 3);
            graficoRanking.Margin = new Padding(3, 3, 6, 8);
            graficoRanking.Name = "graficoRanking";
            graficoRanking.Size = new Size(566, 173);
            graficoRanking.TabIndex = 1;
            dgvReporte.AllowUserToAddRows = false;
            dgvReporte.AllowUserToDeleteRows = false;
            dgvReporte.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvReporte.BorderStyle = BorderStyle.None;
            dgvReporte.ColumnHeadersHeight = 29;
            dgvReporte.Dock = DockStyle.Fill;
            dgvReporte.Location = new Point(0, 0);
            dgvReporte.MultiSelect = false;
            dgvReporte.Name = "dgvReporte";
            dgvReporte.ReadOnly = true;
            dgvReporte.RowHeadersVisible = false;
            dgvReporte.RowHeadersWidth = 51;
            dgvReporte.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvReporte.Size = new Size(1142, 158);
            dgvReporte.TabIndex = 0;
            dgvAnalisis.AllowUserToAddRows = false;
            dgvAnalisis.AllowUserToDeleteRows = false;
            dgvAnalisis.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvAnalisis.BorderStyle = BorderStyle.None;
            dgvAnalisis.ColumnHeadersHeight = 29;
            dgvAnalisis.Dock = DockStyle.Fill;
            dgvAnalisis.Location = new Point(0, 40);
            dgvAnalisis.MultiSelect = false;
            dgvAnalisis.Name = "dgvAnalisis";
            dgvAnalisis.ReadOnly = true;
            dgvAnalisis.RowHeadersVisible = false;
            dgvAnalisis.RowHeadersWidth = 51;
            dgvAnalisis.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvAnalisis.Size = new Size(1142, 118);
            dgvAnalisis.TabIndex = 0;
            panelFiltros.BackColor = Color.White;
            panelFiltros.Controls.Add(filtros);
            panelFiltros.Dock = DockStyle.Fill;
            panelFiltros.Location = new Point(25, 93);
            panelFiltros.Name = "panelFiltros";
            panelFiltros.Size = new Size(1150, 152);
            panelFiltros.TabIndex = 1;
            filtros.ColumnCount = 1;
            filtros.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
            filtros.Controls.Add(fila, 0, 0);
            filtros.Controls.Add(alternables, 0, 1);
            filtros.Controls.Add(acciones, 0, 2);
            filtros.Dock = DockStyle.Fill;
            filtros.Location = new Point(0, 0);
            filtros.Name = "filtros";
            filtros.Padding = new Padding(8);
            filtros.RowCount = 3;
            filtros.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            filtros.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            filtros.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
            filtros.Size = new Size(1150, 152);
            filtros.TabIndex = 0;
            fila.AutoScroll = true;
            fila.Controls.Add(lblFiltro1);
            fila.Controls.Add(cbTipoReporte);
            fila.Controls.Add(lblFiltro2);
            fila.Controls.Add(cbProducto);
            fila.Controls.Add(lblFiltro3);
            fila.Controls.Add(cbZona);
            fila.Dock = DockStyle.Fill;
            fila.Location = new Point(8, 8);
            fila.Margin = new Padding(0);
            fila.Name = "fila";
            fila.Size = new Size(1134, 44);
            fila.TabIndex = 0;
            fila.WrapContents = false;
            lblFiltro1.AutoSize = true;
            lblFiltro1.Location = new Point(4, 8);
            lblFiltro1.Margin = new Padding(4, 8, 4, 0);
            lblFiltro1.Name = "lblFiltro1";
            lblFiltro1.Size = new Size(70, 23);
            lblFiltro1.TabIndex = 0;
            lblFiltro1.Text = "Reporte";
            lblFiltro1.Click += lblFiltro1_Click;
            lblFiltro2.AutoSize = true;
            lblFiltro2.Location = new Point(237, 8);
            lblFiltro2.Margin = new Padding(4, 8, 4, 0);
            lblFiltro2.Name = "lblFiltro2";
            lblFiltro2.Size = new Size(80, 23);
            lblFiltro2.TabIndex = 2;
            lblFiltro2.Text = "Producto";
            lblFiltro3.AutoSize = true;
            lblFiltro3.Location = new Point(585, 8);
            lblFiltro3.Margin = new Padding(4, 8, 4, 0);
            lblFiltro3.Name = "lblFiltro3";
            lblFiltro3.Size = new Size(49, 23);
            lblFiltro3.TabIndex = 4;
            lblFiltro3.Text = "Zona";
            alternables.Controls.Add(filtrosVentas);
            alternables.Controls.Add(filtrosStock);
            alternables.Dock = DockStyle.Fill;
            alternables.Location = new Point(11, 55);
            alternables.Name = "alternables";
            alternables.Size = new Size(1128, 38);
            alternables.TabIndex = 1;
            acciones.AutoScroll = true;
            acciones.Controls.Add(btnGenerarReporte);
            acciones.Controls.Add(btnLimpiar);
            acciones.Controls.Add(btnExportar);
            acciones.Dock = DockStyle.Fill;
            acciones.Location = new Point(8, 96);
            acciones.Margin = new Padding(0);
            acciones.Name = "acciones";
            acciones.Size = new Size(1134, 48);
            acciones.TabIndex = 2;
            acciones.WrapContents = false;
            raiz.ColumnCount = 1;
            raiz.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
            raiz.Controls.Add(encabezado, 0, 0);
            raiz.Controls.Add(panelFiltros, 0, 1);
            raiz.Controls.Add(tarjetas, 0, 2);
            raiz.Controls.Add(lblComparacion, 0, 3);
            raiz.Controls.Add(graficos, 0, 4);
            raiz.Controls.Add(tabs, 0, 5);
            raiz.Controls.Add(lblEstado, 0, 6);
            raiz.Dock = DockStyle.Fill;
            raiz.Location = new Point(0, 0);
            raiz.Name = "raiz";
            raiz.Padding = new Padding(22);
            raiz.RowCount = 7;
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 158F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 92F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 190F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            raiz.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
            raiz.Size = new Size(1200, 820);
            raiz.TabIndex = 0;
            encabezado.Controls.Add(lblTitulo);
            encabezado.Controls.Add(lblContexto);
            encabezado.Dock = DockStyle.Fill;
            encabezado.Location = new Point(25, 25);
            encabezado.Name = "encabezado";
            encabezado.Size = new Size(1150, 62);
            encabezado.TabIndex = 0;
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 16.2F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblTitulo.Location = new Point(649, 0);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(133, 38);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Reportes";
            tarjetas.ColumnCount = 4;
            tarjetas.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            tarjetas.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            tarjetas.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            tarjetas.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            tarjetas.Controls.Add(card0, 0, 0);
            tarjetas.Controls.Add(card1, 1, 0);
            tarjetas.Controls.Add(card2, 2, 0);
            tarjetas.Controls.Add(card3, 3, 0);
            tarjetas.Dock = DockStyle.Fill;
            tarjetas.Location = new Point(25, 251);
            tarjetas.Name = "tarjetas";
            tarjetas.RowCount = 1;
            tarjetas.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            tarjetas.Size = new Size(1150, 86);
            tarjetas.TabIndex = 2;
            card0.BackColor = Color.White;
            card0.Controls.Add(indicador0);
            card0.Controls.Add(tituloIndicador0);
            card0.Dock = DockStyle.Fill;
            card0.Location = new Point(0, 8);
            card0.Margin = new Padding(0, 8, 6, 4);
            card0.Name = "card0";
            card0.Padding = new Padding(12);
            card0.Size = new Size(281, 74);
            card0.TabIndex = 0;
            indicador0.AutoEllipsis = true;
            indicador0.Dock = DockStyle.Fill;
            indicador0.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            indicador0.ForeColor = Color.FromArgb(58, 99, 81);
            indicador0.Location = new Point(12, 34);
            indicador0.Name = "indicador0";
            indicador0.Size = new Size(257, 28);
            indicador0.TabIndex = 0;
            indicador0.Text = "—";
            tituloIndicador0.Dock = DockStyle.Top;
            tituloIndicador0.ForeColor = Color.DimGray;
            tituloIndicador0.Location = new Point(12, 12);
            tituloIndicador0.Name = "tituloIndicador0";
            tituloIndicador0.Size = new Size(257, 22);
            tituloIndicador0.TabIndex = 1;
            tituloIndicador0.Text = "—";
            card1.BackColor = Color.White;
            card1.Controls.Add(indicador1);
            card1.Controls.Add(tituloIndicador1);
            card1.Dock = DockStyle.Fill;
            card1.Location = new Point(293, 8);
            card1.Margin = new Padding(6, 8, 6, 4);
            card1.Name = "card1";
            card1.Padding = new Padding(12);
            card1.Size = new Size(275, 74);
            card1.TabIndex = 1;
            indicador1.AutoEllipsis = true;
            indicador1.Dock = DockStyle.Fill;
            indicador1.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            indicador1.ForeColor = Color.FromArgb(58, 99, 81);
            indicador1.Location = new Point(12, 34);
            indicador1.Name = "indicador1";
            indicador1.Size = new Size(251, 28);
            indicador1.TabIndex = 0;
            indicador1.Text = "—";
            tituloIndicador1.Dock = DockStyle.Top;
            tituloIndicador1.ForeColor = Color.DimGray;
            tituloIndicador1.Location = new Point(12, 12);
            tituloIndicador1.Name = "tituloIndicador1";
            tituloIndicador1.Size = new Size(251, 22);
            tituloIndicador1.TabIndex = 1;
            tituloIndicador1.Text = "—";
            card2.BackColor = Color.White;
            card2.Controls.Add(indicador2);
            card2.Controls.Add(tituloIndicador2);
            card2.Dock = DockStyle.Fill;
            card2.Location = new Point(580, 8);
            card2.Margin = new Padding(6, 8, 6, 4);
            card2.Name = "card2";
            card2.Padding = new Padding(12);
            card2.Size = new Size(275, 74);
            card2.TabIndex = 2;
            indicador2.AutoEllipsis = true;
            indicador2.Dock = DockStyle.Fill;
            indicador2.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            indicador2.ForeColor = Color.FromArgb(58, 99, 81);
            indicador2.Location = new Point(12, 34);
            indicador2.Name = "indicador2";
            indicador2.Size = new Size(251, 28);
            indicador2.TabIndex = 0;
            indicador2.Text = "—";
            tituloIndicador2.Dock = DockStyle.Top;
            tituloIndicador2.ForeColor = Color.DimGray;
            tituloIndicador2.Location = new Point(12, 12);
            tituloIndicador2.Name = "tituloIndicador2";
            tituloIndicador2.Size = new Size(251, 22);
            tituloIndicador2.TabIndex = 1;
            tituloIndicador2.Text = "—";
            card3.BackColor = Color.White;
            card3.Controls.Add(indicador3);
            card3.Controls.Add(tituloIndicador3);
            card3.Dock = DockStyle.Fill;
            card3.Location = new Point(867, 8);
            card3.Margin = new Padding(6, 8, 0, 4);
            card3.Name = "card3";
            card3.Padding = new Padding(12);
            card3.Size = new Size(283, 74);
            card3.TabIndex = 3;
            indicador3.AutoEllipsis = true;
            indicador3.Dock = DockStyle.Fill;
            indicador3.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            indicador3.ForeColor = Color.FromArgb(58, 99, 81);
            indicador3.Location = new Point(12, 34);
            indicador3.Name = "indicador3";
            indicador3.Size = new Size(259, 28);
            indicador3.TabIndex = 0;
            indicador3.Text = "—";
            tituloIndicador3.Dock = DockStyle.Top;
            tituloIndicador3.ForeColor = Color.DimGray;
            tituloIndicador3.Location = new Point(12, 12);
            tituloIndicador3.Name = "tituloIndicador3";
            tituloIndicador3.Size = new Size(259, 22);
            tituloIndicador3.TabIndex = 1;
            tituloIndicador3.Text = "—";
            graficos.ColumnCount = 2;
            graficos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            graficos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            graficos.Controls.Add(graficoEvolucion, 0, 0);
            graficos.Controls.Add(graficoRanking, 1, 0);
            graficos.Dock = DockStyle.Fill;
            graficos.Location = new Point(25, 381);
            graficos.Name = "graficos";
            graficos.RowCount = 1;
            graficos.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
            graficos.Size = new Size(1150, 184);
            graficos.TabIndex = 4;
            tabs.Controls.Add(detalle);
            tabs.Controls.Add(analisis);
            tabs.Dock = DockStyle.Fill;
            tabs.Location = new Point(25, 571);
            tabs.Name = "tabs";
            tabs.SelectedIndex = 0;
            tabs.Size = new Size(1150, 194);
            tabs.TabIndex = 5;
            detalle.Controls.Add(dgvReporte);
            detalle.Controls.Add(lblVacio);
            detalle.Location = new Point(4, 32);
            detalle.Name = "detalle";
            detalle.Size = new Size(1142, 158);
            detalle.TabIndex = 0;
            detalle.Text = "Detalle";
            analisis.Controls.Add(dgvAnalisis);
            analisis.Controls.Add(agrupar);
            analisis.Location = new Point(4, 32);
            analisis.Name = "analisis";
            analisis.Size = new Size(1142, 158);
            analisis.TabIndex = 1;
            analisis.Text = "Agrupar y analizar";
            agrupar.AutoScroll = true;
            agrupar.Controls.Add(lblFiltro7);
            agrupar.Controls.Add(cbAgrupar);
            agrupar.Dock = DockStyle.Top;
            agrupar.Location = new Point(0, 0);
            agrupar.Margin = new Padding(0);
            agrupar.Name = "agrupar";
            agrupar.Size = new Size(1142, 40);
            agrupar.TabIndex = 1;
            agrupar.WrapContents = false;
            lblFiltro7.AutoSize = true;
            lblFiltro7.Location = new Point(4, 8);
            lblFiltro7.Margin = new Padding(4, 8, 4, 0);
            lblFiltro7.Name = "lblFiltro7";
            lblFiltro7.Size = new Size(103, 23);
            lblFiltro7.TabIndex = 0;
            lblFiltro7.Text = "Agrupar por";
            AcceptButton = btnGenerarReporte;
            AutoScaleDimensions = new SizeF(120F, 120F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 820);
            Controls.Add(raiz);
            Font = new Font("Segoe UI", 10F);
            MinimumSize = new Size(1000, 760);
            Name = "FrmReportes";
            Tag = "TituloReportes";
            Text = "Reportes | MF Bebidas";
            WindowState = FormWindowState.Maximized;
            ((System.ComponentModel.ISupportInitialize)numUmbral).EndInit();
            filtrosVentas.ResumeLayout(false);
            filtrosVentas.PerformLayout();
            filtrosStock.ResumeLayout(false);
            filtrosStock.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvReporte).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvAnalisis).EndInit();
            panelFiltros.ResumeLayout(false);
            filtros.ResumeLayout(false);
            fila.ResumeLayout(false);
            fila.PerformLayout();
            alternables.ResumeLayout(false);
            acciones.ResumeLayout(false);
            raiz.ResumeLayout(false);
            encabezado.ResumeLayout(false);
            encabezado.PerformLayout();
            tarjetas.ResumeLayout(false);
            card0.ResumeLayout(false);
            card1.ResumeLayout(false);
            card2.ResumeLayout(false);
            card3.ResumeLayout(false);
            graficos.ResumeLayout(false);
            tabs.ResumeLayout(false);
            detalle.ResumeLayout(false);
            analisis.ResumeLayout(false);
            agrupar.ResumeLayout(false);
            agrupar.PerformLayout();
            ResumeLayout(false);
        }
    }
}
