namespace UI
{
    partial class FrmVentas
    {
        private System.ComponentModel.IContainer components = null;
        private DataGridView dgvProductos;
        private DataGridView dgvCarrito;
        private NumericUpDown nudCantidad;
        private Button btnAgregarProducto;
        private Button btnVerLotes;
        private Button btnRegistrarVenta;
        private Button btnQuitarItem;
        private Button btnCancelarCarrito;
        private Label lblTotal;
        private Label lblCliente;
        private ComboBox cbCliente;
        private Label lblVendedor;
        private TextBox txtVendedor;
        private Label lblZona;
        private TextBox txtZona;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            dgvProductos = new DataGridView();
            dgvCarrito = new DataGridView();
            nudCantidad = new NumericUpDown();
            btnAgregarProducto = new Button();
            btnVerLotes = new Button();
            btnRegistrarVenta = new Button();
            btnQuitarItem = new Button();
            btnCancelarCarrito = new Button();
            lblTotal = new Label();
            lblCliente = new Label();
            cbCliente = new ComboBox();
            lblVendedor = new Label();
            txtVendedor = new TextBox();
            lblZona = new Label();
            txtZona = new TextBox();
            pnlControlesIzq = new FlowLayoutPanel();
            splitContenedorPrincipal = new SplitContainer();
            pnlIzquierdo = new Panel();
            pnlPieIzq = new FlowLayoutPanel();
            pnlDerecho = new Panel();
            tblPrincipal = new TableLayoutPanel();
            pnlCabecera = new FlowLayoutPanel();
            pnlPie = new FlowLayoutPanel();
            ((System.ComponentModel.ISupportInitialize)dgvProductos).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgvCarrito).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudCantidad).BeginInit();
            pnlControlesIzq.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)splitContenedorPrincipal).BeginInit();
            splitContenedorPrincipal.Panel1.SuspendLayout();
            splitContenedorPrincipal.Panel2.SuspendLayout();
            splitContenedorPrincipal.SuspendLayout();
            pnlIzquierdo.SuspendLayout();
            pnlPieIzq.SuspendLayout();
            pnlDerecho.SuspendLayout();
            tblPrincipal.SuspendLayout();
            pnlCabecera.SuspendLayout();
            pnlPie.SuspendLayout();
            SuspendLayout();
            dgvProductos.AllowUserToAddRows = false;
            dgvProductos.AllowUserToDeleteRows = false;
            dgvProductos.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvProductos.BackgroundColor = System.Drawing.Color.White;
            dgvProductos.ColumnHeadersHeight = 30;
            dgvProductos.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvProductos.Dock = DockStyle.Fill;
            dgvProductos.Name = "dgvProductos";
            dgvProductos.ReadOnly = true;
            dgvProductos.RowHeadersVisible = false;
            dgvProductos.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvProductos.TabIndex = 0;
            dgvCarrito.AllowUserToAddRows = false;
            dgvCarrito.AllowUserToDeleteRows = false;
            dgvCarrito.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvCarrito.BackgroundColor = System.Drawing.Color.White;
            dgvCarrito.ColumnHeadersHeight = 30;
            dgvCarrito.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            dgvCarrito.Dock = DockStyle.Fill;
            dgvCarrito.Name = "dgvCarrito";
            dgvCarrito.ReadOnly = true;
            dgvCarrito.RowHeadersVisible = false;
            dgvCarrito.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvCarrito.TabIndex = 0;
            nudCantidad.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            nudCantidad.Maximum = new decimal (new int[] { 1000, 0, 0, 0 });
            nudCantidad.Minimum = new decimal (new int[] { 1, 0, 0, 0 });
            nudCantidad.Margin = new Padding(10);
            nudCantidad.Name = "nudCantidad";
            nudCantidad.Size = new Size(120, 39);
            nudCantidad.TabIndex = 0;
            nudCantidad.TextAlign = HorizontalAlignment.Center;
            nudCantidad.Value = new decimal (new int[] { 1, 0, 0, 0 });
            btnAgregarProducto.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            btnAgregarProducto.FlatStyle = FlatStyle.Flat;
            btnAgregarProducto.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnAgregarProducto.ForeColor = System.Drawing.Color.White;
            btnAgregarProducto.Margin = new Padding(10);
            btnAgregarProducto.Name = "btnAgregarProducto";
            btnAgregarProducto.Size = new Size(230, 60);
            btnAgregarProducto.TabIndex = 1;
            btnAgregarProducto.Text = "Agregar al Carrito";
            btnAgregarProducto.UseVisualStyleBackColor = false;
            btnAgregarProducto.Click += btnAgregarProducto_Click;
            btnVerLotes.BackColor = System.Drawing.ColorTranslator.FromHtml("#2D4D3A");
            btnVerLotes.FlatStyle = FlatStyle.Flat;
            btnVerLotes.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnVerLotes.ForeColor = System.Drawing.Color.White;
            btnVerLotes.Margin = new Padding(10);
            btnVerLotes.Name = "btnVerLotes";
            btnVerLotes.Size = new Size(190, 55);
            btnVerLotes.TabIndex = 2;
            btnVerLotes.Text = "Ver Lotes";
            btnVerLotes.UseVisualStyleBackColor = false;
            btnVerLotes.Click += btnVerLotes_Click;
            btnRegistrarVenta.BackColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            btnRegistrarVenta.FlatStyle = FlatStyle.Flat;
            btnRegistrarVenta.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            btnRegistrarVenta.ForeColor = System.Drawing.Color.White;
            btnRegistrarVenta.Margin = new Padding(15, 12, 15, 12);
            btnRegistrarVenta.Name = "btnRegistrarVenta";
            btnRegistrarVenta.Size = new Size(300, 80);
            btnRegistrarVenta.TabIndex = 3;
            btnRegistrarVenta.Text = "VENDER / FACTURAR";
            btnRegistrarVenta.UseVisualStyleBackColor = false;
            btnRegistrarVenta.Click += btnRegistrarVenta_Click;
            btnQuitarItem.BackColor = System.Drawing.ColorTranslator.FromHtml("#B23B3B");
            btnQuitarItem.Enabled = false;
            btnQuitarItem.FlatStyle = FlatStyle.Flat;
            btnQuitarItem.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnQuitarItem.ForeColor = System.Drawing.Color.White;
            btnQuitarItem.Margin = new Padding(12, 12, 12, 12);
            btnQuitarItem.Name = "btnQuitarItem";
            btnQuitarItem.Size = new Size(190, 60);
            btnQuitarItem.TabIndex = 2;
            btnQuitarItem.Text = "Quitar Ítem";
            btnQuitarItem.UseVisualStyleBackColor = false;
            btnQuitarItem.Click += btnQuitarItem_Click;
            btnCancelarCarrito.BackColor = System.Drawing.ColorTranslator.FromHtml("#5A5A5A");
            btnCancelarCarrito.FlatStyle = FlatStyle.Flat;
            btnCancelarCarrito.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnCancelarCarrito.ForeColor = System.Drawing.Color.White;
            btnCancelarCarrito.Margin = new Padding(12, 12, 12, 12);
            btnCancelarCarrito.Name = "btnCancelarCarrito";
            btnCancelarCarrito.Size = new Size(210, 60);
            btnCancelarCarrito.TabIndex = 1;
            btnCancelarCarrito.Text = "Cancelar Carrito";
            btnCancelarCarrito.UseVisualStyleBackColor = false;
            btnCancelarCarrito.Click += btnCancelarCarrito_Click;
            lblTotal.AutoSize = true;
            lblTotal.BackColor = System.Drawing.ColorTranslator.FromHtml("#FFFFFF");
            lblTotal.BorderStyle = BorderStyle.FixedSingle;
            lblTotal.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTotal.ForeColor = System.Drawing.ColorTranslator.FromHtml("#3A6351");
            lblTotal.Margin = new Padding(20, 10, 40, 10);
            lblTotal.Name = "lblTotal";
            lblTotal.Padding = new Padding(25, 15, 25, 15);
            lblTotal.Size = new Size(340, 90);
            lblTotal.TabIndex = 0;
            lblTotal.Text = "TOTAL: $0";
            lblTotal.TextAlign = ContentAlignment.MiddleLeft;
            lblCliente.AutoSize = true;
            lblCliente.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblCliente.Margin = new Padding(15, 15, 5, 5);
            lblCliente.Name = "lblCliente";
            lblCliente.Size = new Size(77, 23);
            lblCliente.TabIndex = 2;
            lblCliente.Text = "Cliente:";
            cbCliente.DropDownStyle = ComboBoxStyle.DropDownList;
            cbCliente.Font = new Font("Segoe UI", 10F);
            cbCliente.Margin = new Padding(5, 12, 15, 5);
            cbCliente.Name = "cbCliente";
            cbCliente.Size = new Size(340, 31);
            cbCliente.TabIndex = 3;
            cbCliente.SelectedIndexChanged += cbCliente_SelectedIndexChanged;
            lblVendedor.AutoSize = true;
            lblVendedor.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblVendedor.Margin = new Padding(15, 15, 5, 5);
            lblVendedor.Name = "lblVendedor";
            lblVendedor.Size = new Size(93, 23);
            lblVendedor.TabIndex = 0;
            lblVendedor.Text = "Vendedor:";
            txtVendedor.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            txtVendedor.BorderStyle = BorderStyle.FixedSingle;
            txtVendedor.Font = new Font("Segoe UI", 10F);
            txtVendedor.Margin = new Padding(5, 12, 8, 5);
            txtVendedor.Name = "txtVendedor";
            txtVendedor.ReadOnly = true;
            txtVendedor.Size = new Size(260, 30);
            txtVendedor.TabIndex = 1;
            txtVendedor.TabStop = false;
            lblZona.AutoSize = true;
            lblZona.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblZona.Margin = new Padding(15, 15, 5, 5);
            lblZona.Name = "lblZona";
            lblZona.Size = new Size(57, 23);
            lblZona.TabIndex = 4;
            lblZona.Text = "Zona:";
            txtZona.BackColor = System.Drawing.Color.FromArgb(245, 245, 245);
            txtZona.BorderStyle = BorderStyle.FixedSingle;
            txtZona.Font = new Font("Segoe UI", 10F);
            txtZona.ForeColor = System.Drawing.Color.FromArgb(60, 60, 60);
            txtZona.Margin = new Padding(5, 12, 15, 5);
            txtZona.Name = "txtZona";
            txtZona.ReadOnly = true;
            txtZona.Size = new Size(200, 30);
            txtZona.TabIndex = 5;
            txtZona.TabStop = false;
            txtZona.Text = "-";
            pnlControlesIzq.AutoSize = false;
            pnlControlesIzq.BackColor = System.Drawing.Color.FromArgb(225, 235, 228);
            pnlControlesIzq.Controls.Add(nudCantidad);
            pnlControlesIzq.Controls.Add(btnAgregarProducto);
            pnlControlesIzq.Controls.Add(btnVerLotes);
            pnlControlesIzq.Dock = DockStyle.Top;
            pnlControlesIzq.FlowDirection = FlowDirection.LeftToRight;
            pnlControlesIzq.Font = new Font("Segoe UI", 10F);
            pnlControlesIzq.Location = new Point(0, 0);
            pnlControlesIzq.Name = "pnlControlesIzq";
            pnlControlesIzq.Padding = new Padding(18, 18, 15, 15);
            pnlControlesIzq.Size = new Size(900, 95);
            pnlControlesIzq.TabIndex = 1;
            pnlControlesIzq.WrapContents = true;
            splitContenedorPrincipal.Dock = DockStyle.Fill;
            splitContenedorPrincipal.FixedPanel = FixedPanel.Panel1;
            splitContenedorPrincipal.Location = new Point(0, 0);
            splitContenedorPrincipal.Name = "splitContenedorPrincipal";
            splitContenedorPrincipal.Panel1.Controls.Add(pnlIzquierdo);
            splitContenedorPrincipal.Panel1MinSize = 600;
            splitContenedorPrincipal.Panel2.Controls.Add(pnlDerecho);
            splitContenedorPrincipal.Panel2MinSize = 350;
            splitContenedorPrincipal.Size = new Size(1700, 765);
            splitContenedorPrincipal.SplitterDistance = 900;
            splitContenedorPrincipal.SplitterWidth = 10;
            splitContenedorPrincipal.TabIndex = 0;
            pnlIzquierdo.AutoScroll = true;
            pnlIzquierdo.BackColor = System.Drawing.Color.White;
            pnlIzquierdo.Controls.Add(dgvProductos);
            pnlIzquierdo.Controls.Add(pnlControlesIzq);
            pnlIzquierdo.Controls.Add(pnlPieIzq);
            pnlIzquierdo.Dock = DockStyle.Fill;
            pnlIzquierdo.Margin = new Padding(0);
            pnlIzquierdo.Name = "pnlIzquierdo";
            pnlIzquierdo.Size = new Size(900, 765);
            pnlIzquierdo.TabIndex = 0;
            pnlPieIzq.AutoScroll = true;
            pnlPieIzq.BackColor = System.Drawing.Color.FromArgb(248, 248, 248);
            pnlPieIzq.Dock = DockStyle.Bottom;
            pnlPieIzq.Font = new Font("Segoe UI", 9F);
            pnlPieIzq.ForeColor = System.Drawing.Color.FromArgb(80, 80, 80);
            pnlPieIzq.Location = new Point(0, 725);
            pnlPieIzq.Name = "pnlPieIzq";
            pnlPieIzq.Size = new Size(900, 40);
            pnlPieIzq.TabIndex = 2;
            pnlPieIzq.WrapContents = false;
            Label infoLbl = new Label
            {
                AutoSize = true,
                Margin = new Padding(12, 10, 5, 5),
                Text = "💡 Seleccioná un producto, elegí la cantidad y tocá AGREGAR."
            };
            pnlPieIzq.Controls.Add(infoLbl);
            pnlDerecho.AutoScroll = true;
            pnlDerecho.BackColor = System.Drawing.Color.White;
            pnlDerecho.Controls.Add(dgvCarrito);
            pnlDerecho.Dock = DockStyle.Fill;
            pnlDerecho.Margin = new Padding(0);
            pnlDerecho.Name = "pnlDerecho";
            pnlDerecho.Size = new Size(790, 765);
            pnlDerecho.TabIndex = 0;
            tblPrincipal.AutoScroll = true;
            tblPrincipal.BackColor = System.Drawing.Color.FromArgb(240, 240, 240);
            tblPrincipal.ColumnCount = 1;
            tblPrincipal.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tblPrincipal.Controls.Add(pnlCabecera, 0, 0);
            tblPrincipal.Controls.Add(splitContenedorPrincipal, 0, 1);
            tblPrincipal.Controls.Add(pnlPie, 0, 2);
            tblPrincipal.Dock = DockStyle.Fill;
            tblPrincipal.GrowStyle = TableLayoutPanelGrowStyle.FixedSize;
            tblPrincipal.Margin = new Padding(0);
            tblPrincipal.Name = "tblPrincipal";
            tblPrincipal.RowCount = 3;
            tblPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 95F));
            tblPrincipal.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tblPrincipal.RowStyles.Add(new RowStyle(SizeType.Absolute, 110F));
            tblPrincipal.Size = new Size(1700, 970);
            tblPrincipal.TabIndex = 0;
            pnlCabecera.AutoScroll = true;
            pnlCabecera.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlCabecera.Controls.Add(lblVendedor);
            pnlCabecera.Controls.Add(txtVendedor);
            pnlCabecera.Controls.Add(lblCliente);
            pnlCabecera.Controls.Add(cbCliente);
            pnlCabecera.Controls.Add(lblZona);
            pnlCabecera.Controls.Add(txtZona);
            pnlCabecera.Dock = DockStyle.Fill;
            pnlCabecera.FlowDirection = FlowDirection.LeftToRight;
            pnlCabecera.Font = new Font("Segoe UI", 10F);
            pnlCabecera.Margin = new Padding(0);
            pnlCabecera.Name = "pnlCabecera";
            pnlCabecera.Padding = new Padding(8);
            pnlCabecera.Size = new Size(1700, 95);
            pnlCabecera.TabIndex = 0;
            pnlCabecera.WrapContents = true;
            pnlPie.AutoScroll = true;
            pnlPie.BackColor = System.Drawing.Color.FromArgb(244, 244, 244);
            pnlPie.Controls.Add(lblTotal);
            pnlPie.Controls.Add(btnCancelarCarrito);
            pnlPie.Controls.Add(btnQuitarItem);
            pnlPie.Controls.Add(btnRegistrarVenta);
            pnlPie.Dock = DockStyle.Fill;
            pnlPie.FlowDirection = FlowDirection.LeftToRight;
            pnlPie.Font = new Font("Segoe UI", 10F);
            pnlPie.Margin = new Padding(0);
            pnlPie.Name = "pnlPie";
            pnlPie.Padding = new Padding(15);
            pnlPie.Size = new Size(1700, 110);
            pnlPie.TabIndex = 2;
            pnlPie.WrapContents = true;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            BackColor = System.Drawing.Color.FromArgb(240, 240, 240);
            ClientSize = new Size(1700, 970);
            Controls.Add(tblPrincipal);
            Font = new Font("Segoe UI", 10F);
            MinimumSize = new Size(1400, 900);
            Name = "FrmVentas";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Gestión de Ventas";
            WindowState = FormWindowState.Maximized;
            Load += FrmVentas_Load;
            ((System.ComponentModel.ISupportInitialize)dgvProductos).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgvCarrito).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudCantidad).EndInit();
            pnlControlesIzq.ResumeLayout(false);
            splitContenedorPrincipal.Panel1.ResumeLayout(false);
            splitContenedorPrincipal.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)splitContenedorPrincipal).EndInit();
            splitContenedorPrincipal.ResumeLayout(false);
            pnlIzquierdo.ResumeLayout(false);
            pnlPieIzq.ResumeLayout(false);
            pnlDerecho.ResumeLayout(false);
            tblPrincipal.ResumeLayout(false);
            tblPrincipal.PerformLayout();
            pnlCabecera.ResumeLayout(false);
            pnlCabecera.PerformLayout();
            pnlPie.ResumeLayout(false);
            pnlPie.PerformLayout();
            ResumeLayout(false);
        }

        private FlowLayoutPanel pnlControlesIzq;
        private SplitContainer splitContenedorPrincipal;
        private Panel pnlIzquierdo;
        private FlowLayoutPanel pnlPieIzq;
        private Panel pnlDerecho;
        private TableLayoutPanel tblPrincipal;
        private FlowLayoutPanel pnlCabecera;
        private FlowLayoutPanel pnlPie;
    }
}
